var annotated_dup =
[
    [ "pycanha", "namespacepycanha.html", [
      [ "conduction", null, [
        [ "CellLink", "structpycanha_1_1conduction_1_1CellLink.html", "structpycanha_1_1conduction_1_1CellLink" ],
        [ "TmmBuildOptions", "structpycanha_1_1conduction_1_1TmmBuildOptions.html", "structpycanha_1_1conduction_1_1TmmBuildOptions" ],
        [ "BuildDiagnostic", "structpycanha_1_1conduction_1_1BuildDiagnostic.html", null ],
        [ "TmmBuildReport", "structpycanha_1_1conduction_1_1TmmBuildReport.html", "structpycanha_1_1conduction_1_1TmmBuildReport" ],
        [ "MeridianProfile", "classpycanha_1_1conduction_1_1MeridianProfile.html", "classpycanha_1_1conduction_1_1MeridianProfile" ],
        [ "GeometryItem", "classpycanha_1_1conduction_1_1GeometryItem.html", null ]
      ] ],
      [ "gmm", null, [
        [ "cutting", null, [
          [ "CutBackend", "classpycanha_1_1gmm_1_1cutting_1_1CutBackend.html", null ],
          [ "ManifoldCutBackend", "classpycanha_1_1gmm_1_1cutting_1_1ManifoldCutBackend.html", null ],
          [ "ProxyMeta", "structpycanha_1_1gmm_1_1cutting_1_1ProxyMeta.html", null ]
        ] ],
        [ "mesh", null, [
          [ "ops", null, [
            [ "detail", null, [
              [ "ValidateEdgeHash", "structpycanha_1_1gmm_1_1mesh_1_1ops_1_1detail_1_1ValidateEdgeHash.html", null ]
            ] ]
          ] ],
          [ "detail", null, [
            [ "SamplingPlan", "structpycanha_1_1gmm_1_1mesh_1_1detail_1_1SamplingPlan.html", null ]
          ] ]
        ] ],
        [ "detail", null, [
          [ "PlaneBasis", "structpycanha_1_1gmm_1_1detail_1_1PlaneBasis.html", null ],
          [ "SphereFrame", "structpycanha_1_1gmm_1_1detail_1_1SphereFrame.html", null ]
        ] ],
        [ "GeometryModel", "classpycanha_1_1gmm_1_1GeometryModel.html", null ],
        [ "BulkMaterial", "classpycanha_1_1gmm_1_1BulkMaterial.html", "classpycanha_1_1gmm_1_1BulkMaterial" ],
        [ "Color", "classpycanha_1_1gmm_1_1Color.html", "classpycanha_1_1gmm_1_1Color" ],
        [ "OpticalMaterial", "classpycanha_1_1gmm_1_1OpticalMaterial.html", "classpycanha_1_1gmm_1_1OpticalMaterial" ],
        [ "MeshOptions", "structpycanha_1_1gmm_1_1MeshOptions.html", null ],
        [ "ThermalMesh", "classpycanha_1_1gmm_1_1ThermalMesh.html", "classpycanha_1_1gmm_1_1ThermalMesh" ],
        [ "TriMesh", "classpycanha_1_1gmm_1_1TriMesh.html", "classpycanha_1_1gmm_1_1TriMesh" ],
        [ "UvMesher", "classpycanha_1_1gmm_1_1UvMesher.html", null ],
        [ "Cone", "classpycanha_1_1gmm_1_1Cone.html", null ],
        [ "Cube", "classpycanha_1_1gmm_1_1Cube.html", null ],
        [ "Cylinder", "classpycanha_1_1gmm_1_1Cylinder.html", null ],
        [ "Disc", "classpycanha_1_1gmm_1_1Disc.html", null ],
        [ "Paraboloid", "classpycanha_1_1gmm_1_1Paraboloid.html", null ],
        [ "Quadrilateral", "classpycanha_1_1gmm_1_1Quadrilateral.html", null ],
        [ "Rectangle", "classpycanha_1_1gmm_1_1Rectangle.html", null ],
        [ "Sphere", "classpycanha_1_1gmm_1_1Sphere.html", null ],
        [ "Triangle", "classpycanha_1_1gmm_1_1Triangle.html", null ],
        [ "CoordinateTransformation", "classpycanha_1_1gmm_1_1CoordinateTransformation.html", null ],
        [ "Geometry", "classpycanha_1_1gmm_1_1Geometry.html", null ],
        [ "GeometryGroup", "classpycanha_1_1gmm_1_1GeometryGroup.html", null ],
        [ "GeometryGroupCutted", "classpycanha_1_1gmm_1_1GeometryGroupCutted.html", null ],
        [ "GeometryItem", "classpycanha_1_1gmm_1_1GeometryItem.html", null ]
      ] ],
      [ "detail", null, [
        [ "EntityOps", "structpycanha_1_1detail_1_1EntityOps.html", null ],
        [ "InterpLocation", "structpycanha_1_1detail_1_1InterpLocation.html", null ]
      ] ],
      [ "radiative", null, [
        [ "detail", null, [
          [ "BlueEstimate", "structpycanha_1_1radiative_1_1detail_1_1BlueEstimate.html", null ],
          [ "ExchangeInputs", "structpycanha_1_1radiative_1_1detail_1_1ExchangeInputs.html", null ],
          [ "VfAccumImpl", "classpycanha_1_1radiative_1_1detail_1_1VfAccumImpl.html", null ],
          [ "ExchangeAccumImpl", "classpycanha_1_1radiative_1_1detail_1_1ExchangeAccumImpl.html", null ],
          [ "SolarAccumImpl", "classpycanha_1_1radiative_1_1detail_1_1SolarAccumImpl.html", "classpycanha_1_1radiative_1_1detail_1_1SolarAccumImpl" ],
          [ "PhysicalDeviceCheck", "structpycanha_1_1radiative_1_1detail_1_1PhysicalDeviceCheck.html", null ],
          [ "DeviceImpl", "classpycanha_1_1radiative_1_1detail_1_1DeviceImpl.html", null ],
          [ "GpuBuffer", "structpycanha_1_1radiative_1_1detail_1_1GpuBuffer.html", null ],
          [ "InstanceDataGpu", "structpycanha_1_1radiative_1_1detail_1_1InstanceDataGpu.html", null ],
          [ "PushConstants", "structpycanha_1_1radiative_1_1detail_1_1PushConstants.html", null ],
          [ "SceneImpl", "classpycanha_1_1radiative_1_1detail_1_1SceneImpl.html", "classpycanha_1_1radiative_1_1detail_1_1SceneImpl" ],
          [ "WeightTable", "classpycanha_1_1radiative_1_1detail_1_1WeightTable.html", null ],
          [ "AssemblyTuning", "structpycanha_1_1radiative_1_1detail_1_1AssemblyTuning.html", null ],
          [ "Weighting", "classpycanha_1_1radiative_1_1detail_1_1Weighting.html", null ],
          [ "RowEntries", "structpycanha_1_1radiative_1_1detail_1_1RowEntries.html", null ],
          [ "DenseCells", "structpycanha_1_1radiative_1_1detail_1_1DenseCells.html", null ],
          [ "SparseCells", "structpycanha_1_1radiative_1_1detail_1_1SparseCells.html", null ]
        ] ],
        [ "VfAccumulator", "classpycanha_1_1radiative_1_1VfAccumulator.html", null ],
        [ "ExchangeAccumulator", "classpycanha_1_1radiative_1_1ExchangeAccumulator.html", null ],
        [ "SolarAccumulator", "classpycanha_1_1radiative_1_1SolarAccumulator.html", null ],
        [ "AggregateResult", "structpycanha_1_1radiative_1_1AggregateResult.html", null ],
        [ "DeviceInfo", "structpycanha_1_1radiative_1_1DeviceInfo.html", null ],
        [ "Device", "classpycanha_1_1radiative_1_1Device.html", null ],
        [ "MaterialTable", "structpycanha_1_1radiative_1_1MaterialTable.html", null ],
        [ "MemoryEstimate", "structpycanha_1_1radiative_1_1MemoryEstimate.html", null ],
        [ "TraceStats", "structpycanha_1_1radiative_1_1TraceStats.html", null ],
        [ "VfResult", "structpycanha_1_1radiative_1_1VfResult.html", null ],
        [ "ExchangeResult", "structpycanha_1_1radiative_1_1ExchangeResult.html", null ],
        [ "SolarResult", "structpycanha_1_1radiative_1_1SolarResult.html", null ],
        [ "SolarState", "structpycanha_1_1radiative_1_1SolarState.html", null ],
        [ "RadiativeScene", "classpycanha_1_1radiative_1_1RadiativeScene.html", null ],
        [ "ScenePart", "structpycanha_1_1radiative_1_1ScenePart.html", null ],
        [ "TraceSettings", "structpycanha_1_1radiative_1_1TraceSettings.html", null ],
        [ "TriangulationConfig", "structpycanha_1_1radiative_1_1TriangulationConfig.html", null ],
        [ "AccumConfig", "structpycanha_1_1radiative_1_1AccumConfig.html", null ],
        [ "PhysicalDeviceCheck", "structpycanha_1_1radiative_1_1PhysicalDeviceCheck.html", null ]
      ] ],
      [ "random_generators", null, [
        [ "RealGenerator", "classpycanha_1_1random__generators_1_1RealGenerator.html", null ],
        [ "IntGenerator", "classpycanha_1_1random__generators_1_1IntGenerator.html", null ]
      ] ],
      [ "ESATANReader", "classpycanha_1_1ESATANReader.html", null ],
      [ "Entity", "classpycanha_1_1Entity.html", "classpycanha_1_1Entity" ],
      [ "Formula", "classpycanha_1_1Formula.html", "classpycanha_1_1Formula" ],
      [ "ParameterFormula", "classpycanha_1_1ParameterFormula.html", null ],
      [ "ValueFormula", "classpycanha_1_1ValueFormula.html", null ],
      [ "ExpressionFormula", "classpycanha_1_1ExpressionFormula.html", "classpycanha_1_1ExpressionFormula" ],
      [ "DerivativeParameterRegistry", "classpycanha_1_1DerivativeParameterRegistry.html", null ],
      [ "Formulas", "classpycanha_1_1Formulas.html", null ],
      [ "Parameters", "classpycanha_1_1Parameters.html", "classpycanha_1_1Parameters" ],
      [ "TimeVariable", "classpycanha_1_1TimeVariable.html", null ],
      [ "TemperatureVariable", "classpycanha_1_1TemperatureVariable.html", null ],
      [ "CallbackContext", "classpycanha_1_1CallbackContext.html", null ],
      [ "CallbackRegistry", "classpycanha_1_1CallbackRegistry.html", null ],
      [ "IntPairHash", "structpycanha_1_1IntPairHash.html", null ],
      [ "Solver", "classpycanha_1_1Solver.html", "classpycanha_1_1Solver" ],
      [ "SolverOutputConfig", "structpycanha_1_1SolverOutputConfig.html", null ],
      [ "SolverRegistry", "classpycanha_1_1SolverRegistry.html", null ],
      [ "SteadyStateSolver", "classpycanha_1_1SteadyStateSolver.html", null ],
      [ "SSLU", "classpycanha_1_1SSLU.html", null ],
      [ "TransientSolver", "classpycanha_1_1TransientSolver.html", null ],
      [ "TSCN", "classpycanha_1_1TSCN.html", null ],
      [ "TSCNRL", "classpycanha_1_1TSCNRL.html", null ],
      [ "TSCNRLDS", "classpycanha_1_1TSCNRLDS.html", null ],
      [ "TSCNRLDS_JACOBIAN", "classpycanha_1_1TSCNRLDS__JACOBIAN.html", null ],
      [ "DataModel", "classpycanha_1_1DataModel.html", null ],
      [ "DataModelStore", "classpycanha_1_1DataModelStore.html", null ],
      [ "DataTableStore", "classpycanha_1_1DataTableStore.html", null ],
      [ "DenseMatrixTimeSeries", "classpycanha_1_1DenseMatrixTimeSeries.html", null ],
      [ "DenseTimeSeries", "classpycanha_1_1DenseTimeSeries.html", null ],
      [ "LookupTable1D", "classpycanha_1_1LookupTable1D.html", null ],
      [ "LookupTableVec1D", "classpycanha_1_1LookupTableVec1D.html", null ],
      [ "NamedConstants", "classpycanha_1_1NamedConstants.html", null ],
      [ "SparseTimeSeries", "classpycanha_1_1SparseTimeSeries.html", null ],
      [ "ThermalData", "classpycanha_1_1ThermalData.html", null ],
      [ "ConductiveCouplings", "classpycanha_1_1ConductiveCouplings.html", null ],
      [ "Coupling", "classpycanha_1_1Coupling.html", "classpycanha_1_1Coupling" ],
      [ "CouplingMatrices", "classpycanha_1_1CouplingMatrices.html", "classpycanha_1_1CouplingMatrices" ],
      [ "Couplings", "classpycanha_1_1Couplings.html", null ],
      [ "LiteralString", "classpycanha_1_1LiteralString.html", null ],
      [ "Node", "classpycanha_1_1Node.html", "classpycanha_1_1Node" ],
      [ "Nodes", "classpycanha_1_1Nodes.html", "classpycanha_1_1Nodes" ],
      [ "RadiativeCouplings", "classpycanha_1_1RadiativeCouplings.html", null ],
      [ "EntitiesHelper", "classpycanha_1_1EntitiesHelper.html", null ],
      [ "ThermalMathematicalModel", "classpycanha_1_1ThermalMathematicalModel.html", null ],
      [ "ThermalModel", "classpycanha_1_1ThermalModel.html", "classpycanha_1_1ThermalModel" ],
      [ "ThermalNetwork", "classpycanha_1_1ThermalNetwork.html", null ],
      [ "ProfileResult", "structpycanha_1_1ProfileResult.html", null ],
      [ "InstrumentationSession", "structpycanha_1_1InstrumentationSession.html", null ],
      [ "Instrumentor", "classpycanha_1_1Instrumentor.html", null ],
      [ "InstrumentationTimer", "classpycanha_1_1InstrumentationTimer.html", null ],
      [ "LogRecord", "structpycanha_1_1LogRecord.html", "structpycanha_1_1LogRecord" ],
      [ "LogDrain", "structpycanha_1_1LogDrain.html", null ]
    ] ]
];